benchmarks = '../../benchmarks/**/*.bril'
extract = 'total_dyn_inst: (\d+)'
timeout=60

[runs.baseline]
pipeline = [
  "bril2json",
  "brili -p {args}",
]

[runs.enhanced_dse]
pipeline = [
    "bril2json",
    "python3 enhanced_dse.py",
    "brili -p {args}",
]